---

- name: download drivers
  ansible.windows.win_get_url:
    url: '{{ item.url }}'
    dest: '{{ winpe_temp_directory }}\{{ item.url | urlsplit("path") | basename }}'
  loop: '{{ winpe_drivers }}'

- name: extract drivers
  community.windows.win_unzip:
    src: '{{ winpe_temp_directory }}\{{ item.url | urlsplit("path") | basename }}'
    dest: '{{ winpe_temp_directory }}\{{ item.name }}'
  when: item.enable
  loop: '{{ winpe_drivers }}'

- name: clean up driver files
  ansible.windows.win_file:
    path: '{{ winpe_temp_directory }}\{{ item.url | urlsplit("path") | basename }}'
    state: absent
  loop: '{{ winpe_drivers }}'
