---
- name: download drivers
  win_get_url:
    url: '{{ item.url }}'
    dest: '{{ temp_directory }}\{{ item.url | urlsplit("path") | basename }}'
  loop: '{{ drivers }}'

- name: extract drivers
  win_unzip:
    src: '{{ temp_directory }}\{{ item.url | urlsplit("path") | basename }}'
    dest: '{{ temp_directory }}\{{ item.name }}'
  when: item.enable
  loop: '{{ drivers }}'

- name: clean up driver files
  win_file:
    path: '{{ temp_directory }}\{{ item.url | urlsplit("path") | basename }}'
    state: absent
  loop: '{{ drivers }}'