---
- debug:
    msg: "{{ os_level }}"

- name: set winpe_name
  set_fact:
    winpe_name: '{{ winpe_name }}_ps'
  when: enable_powershell_modules

- name: set winpe_name with debug
  set_fact:
    winpe_name: '{{ winpe_name }}_debug'
  when: enable_script_debug

- name: install adk
  include_tasks: "{{ os_product_type }}.yml"

- name: copy winpeshl.ini file
  win_copy:
    src: winpeshl.ini
    dest: '{{ temp_directory }}\winpeshl.ini'
  when: enable_autostart|bool

- name: create files
  win_template:
    src: '{{ item }}'
    dest: '{{ temp_directory }}\{{ item }}'
  loop:
    - init.cmd
    - setsysname.cmd

- name: download curl
  win_get_url:
    url: '{{ curl_download_url }}'
    dest: '{{ temp_directory }}\curl.zip'

- name: unzip curl
  win_unzip:
    src: '{{ temp_directory }}\curl.zip'
    dest: '{{ temp_directory }}'
    creates: '{{ temp_directory }}\{{ curl_directory }}'

- name: load drivers
  include_tasks: drivers.yml
  when: load_drivers|bool

- name: create a working copy of the windows pe files
  win_shell: '"..\\Deployment Tools\\DandISetEnv.bat" & copype amd64 C:\{{ winpe_name }}'
  args:
    executable: cmd
    chdir: C:\ADK\Assessment and Deployment Kit\Windows Preinstallation Environment
    creates: C:\{{ winpe_name }}

- name: copy script file
  win_template:
    src: create_winpe.ps1
    dest: '{{ temp_directory }}\create_winpe.ps1'

- name: copy files and modules into winpe
  win_shell: '{{ temp_directory }}\create_winpe.ps1'

- name: create winpe iso file
  win_shell: '"..\\Deployment Tools\\DandISetEnv.bat" & MakeWinPEMedia /ISO C:\{{ winpe_name }} {{ temp_directory }}\{{ winpe_name }}.iso'
  args:
    executable: cmd
    chdir: C:\ADK\Assessment and Deployment Kit\Windows Preinstallation Environment

- name: copy winpe iso file
  win_copy:
    src: '{{ temp_directory }}\{{ winpe_name }}.iso'
    dest: '{{ smb_share }}\{{ destination_file_location }}\'
    remote_src: yes
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  vars:
    ansible_become_user: '{{ smb_share_username }}'
    ansible_become_pass: '{{ smb_share_password }}'

- name: remove boot prompt
  win_file:
    path: C:\{{ winpe_name }}\media\Boot\Bootfix.bin
    state: absent

- name: create winpe no prompt iso file
  win_shell: '"..\\Deployment Tools\\DandISetEnv.bat" & MakeWinPEMedia /ISO C:\{{ winpe_name }} {{ temp_directory }}\{{ winpe_name }}_no_prompt.iso'
  args:
    executable: cmd
    chdir: C:\ADK\Assessment and Deployment Kit\Windows Preinstallation Environment

- name: copy winpe no prompt iso file
  win_copy:
    src: '{{ temp_directory }}\{{ winpe_name }}_no_prompt.iso'
    dest: '{{ smb_share }}\{{ destination_file_location }}\'
    remote_src: yes
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  vars:
    ansible_become_user: '{{ smb_share_username }}'
    ansible_become_pass: '{{ smb_share_password }}'

- name: clean up temp files
  win_file:
    path: '{{ temp_directory }}\{{ item }}'
    state: absent
  loop:
    - winpeshl.ini
    - init.cmd
    - setsysname.cmd
    - create_winpe.ps1
    - curl.zip
    - '{{ curl_directory }}'
    - '{{ winpe_name }}.iso'
    - '{{ winpe_name }}_no_prompt.iso'

- name: clean winpe files
  win_file:
    path: C:\{{ winpe_name }}
    state: absent