---

- name: check adk iso file
  win_stat:
    path: "{{ win_adk_iso_path }}"
  register: adk_iso_file
  when: (":" in win_adk_iso_path)

- name: download adk iso file
  win_get_url:
    dest: "{{ win_adk_iso_path }}"
    url: "{{ win_adk_download_url }}"
  register: download_adk_iso
  until: download_adk_iso is success
  delay: 3
  retries: 5
  when: (":" in win_adk_iso_path) and (not adk_iso_file.stat.exists)

- block:
    - name: mount adk iso
      win_disk_image:
        image_path: "{{ win_adk_iso_path }}"
        state: present
      register: adk_disk_image_out

    - name: install windows adk
      win_package:
        path: '{{ adk_disk_image_out.mount_paths[0] }}adksetup.exe'
        product_id: '{{ win_adk_product_id }}'
        arguments: /quiet /installpath c:\ADK /norestart /ceip off /features {{ win_adk_features }}
  always:
    - name: unmount adk iso
      win_disk_image:
        image_path: "{{ win_adk_iso_path }}"
        state: absent

- name: check adk winpe addon iso file
  win_stat:
    path: "{{ win_adk_winpe_addon_iso_path }}"
  register: adk_winpe_addon_iso_file
  when: (":" in win_adk_winpe_addon_iso_path)

- name: download adk winpe addon iso file
  win_get_url:
    dest: "{{ win_adk_winpe_addon_iso_path }}"
    url: "{{ win_adk_winpe_addon_download_url }}"
  register: download_adk_winpe_addon_iso
  until: download_adk_winpe_addon_iso is success
  delay: 3
  retries: 5
  when: (":" in win_adk_winpe_addon_iso_path) and (not adk_winpe_addon_iso_file.stat.exists)

- block:
    - name: mount adk winpe addon iso
      win_disk_image:
        image_path: "{{ win_adk_winpe_addon_iso_path }}"
        state: present
      register: adk_winpe_addon_disk_image_out

    - name: install windows adk winpe addon
      win_package:
        path: '{{ adk_winpe_addon_disk_image_out.mount_paths[0] }}adkwinpesetup.exe'
        product_id: '{{ win_adk_winpe_addon_product_id }}'
        arguments: /quiet /installpath c:\ADK /norestart /ceip off /features {{ win_adk_winpe_addon_features }}
  always:
    - name: unmount adk winpe iso
      win_disk_image:
        image_path: "{{ win_adk_winpe_addon_iso_path }}"
        state: absent