- name: generate_winpe
  hosts: '*_role_wadk'
  become_method: runas
  become: no

  pre_tasks:
    - block:
        - name: add pcsx module
          win_psmodule:
            name: Pscx
            state: present
            allow_clobber: yes
      rescue:
        - name: add pcsx module (retry with allow_clobber disabled)
          win_psmodule:
            name: Pscx
            state: present
          ignore_errors: yes

        - name: add pcsx module (retry with allow_clobber re-enabled)
          win_psmodule:
            name: Pscx
            state: present
            allow_clobber: yes

    - name: install 7-zip
      win_chocolatey:
        name: 7zip.install
        state: present

  roles:
    - winpe