---

- name: generate_winpe
  hosts: '*_role_wadk'
  become_method: ansible.builtin.runas
  become: false
  vars:
    winpe_smb_share_username: "{{ lookup('env', 'SMB_SHARE_USERNAME') | default(smb_share_username) }}"
    winpe_smb_share_password: "{{ lookup('env', 'SMB_SHARE_PASSWORD') | default(smb_share_password) }}"

  pre_tasks:
    - name: add pcsx module
      block:
        - name: add pcsx module
          community.windows.win_psmodule:
            name: Pscx
            state: present
            allow_clobber: true
      rescue:
        - name: add pcsx module (retry with allow_clobber disabled)
          community.windows.win_psmodule:
            name: Pscx
            state: present
          failed_when: false

        - name: add pcsx module (retry with allow_clobber re-enabled)
          community.windows.win_psmodule:
            name: Pscx
            state: present
            allow_clobber: true

    - name: install 7-zip
      chocolatey.chocolatey.win_chocolatey:
        name: 7zip.install
        state: present

  roles:
    - winpe
