---

- name: Remove Windows Servers
  hosts: all
  gather_facts: false
  connection: local
  become: false
  vars_files:
    - node-config/node-kubevirt.yml

  roles:
    - role: ansible-role-kubevirt
      role_action: deprovision
      delegate_to: localhost
      run_once: true
