---

- name: provision hosts on vmware
  hosts: localhost
  gather_facts: false
  become: false
  vars_files:
    - node-config/node-vmware.yml
  roles:
    - ansible-role-vmware

  post_tasks:
    - name: add hosts to winpe group
      ansible.builtin.add_host:
        name: "{{ item.item.name }}"
        ansible_host: "{{ item.item.networks[0].ip | default(item.instance.guest.ipAddress) }}"
        ansible_port: "{{ item.item.ansible_port | default(ansible_port) | default('5986') }}"
        groups: tag_role_wadk,tag_app_winpe
      loop: "{{ guest_ip_address.results }}"
      when: ('winwaik' in item.invocation.module_args.name)
      changed_when: false
      tags:
        - addhost

    - name: wait for systems to be available
      ansible.builtin.wait_for_connection:
        delay: 10
        timeout: 300
      vars:
        ansible_port: 5986
        ansible_connection: winrm
        ansible_winrm_transport: credssp
        ansible_winrm_server_cert_validation: ignore
      delegate_to: "{{ hostvars[item].ansible_host }}"
      loop: "{{ groups.tag_role_wadk }}"
